// Types are inferred from Zod schemas defined in ./schemas.ts
// Source of truth: http://localhost:8080/v3/api-docs (Swagger)
export type {
  ArtistDTO,
  ArtistPayload,
  ArtistEntity,
  MusicGenreDTO,
  MusicGenrePayload,
  MusicGenreEntity,
  SalesChannelDTO,
  SalesChannelPayload,
  SalesChannelEntity,
  AddressDTO,
  AddressPayload,
  AddressEntity,
  CustomerDTO,
  CustomerPayload,
  CustomerEntity,
  RecordDTO,
  RecordPayload,
  PurchaseItemDTO,
  PurchaseItemPayload,
  PurchaseDTO,
  PurchasePayload,
  SaleItemDTO,
  SaleItemPayload,
  SaleDTO,
  SalePayload,
  DetailedRevenueDTO,
  RevenueSummaryDTO,
  ChannelRevenueDTO,
  ProfitPerItemDTO,
  RecordSearchParams,
  RecordStatusValue,
  OrderStatusValue,
} from './schemas';
